permalink: /:year/:month/:day/:title/
url: http://iashub.apps.cloud.gov
baseurl: ""
output: web
topnav_title: IAS Hub
site_title: One stop shop for IAS team members
company_name: US General Services Administration
github_editme_path: GSA/iashub/edit/reviews
# disqus_shortname:
host: 127.0.0.1
port: 4009

exclude:
  - _site
  - _drafts
  - vendor
  - configs/

feedback_email: mark.vogelgesang@gsa.gov


highlighter: rouge
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge


collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: home_sidebar
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true
      sidebar: tags_sidebar



# the description is used in the feed.xml file
description: "Intended as a documentation theme based on Jekyll for technical writers documenting software and other technical products, this theme has all the elements you would need to handle multiple products with both multi-level sidebar navigation, tags, and other documentation features."
